import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const GA_MEASUREMENT_ID = "G-BDNTQ1JGKC";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "optional",
  fallback: ["system-ui", "-apple-system", "sans-serif"],
});

export const viewport: Viewport = {
  themeColor: "#08090a",
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  metadataBase: new URL("https://www.iptvupg.com"),
  title: {
    default: "Best IPTV Service 2026 — 24,000+ Channels in 4K | IPTV UPG",
    template: "%s | IPTV UPG",
  },
  description:
    "Best IPTV Service of 2026 — IPTV UPG streams 24,000+ live channels & 120,000+ movies in 4K. Free trial, instant activation, plans from $7.50/mo. 7-day money-back guarantee.",
  authors: [{ name: "IPTV UPG" }],
  creator: "IPTV UPG",
  publisher: "IPTV UPG",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    // No root-level canonical: every page declares its own to avoid silently
    // inheriting the homepage URL on routes that forget to set one.
    types: {
      "application/rss+xml": "https://www.iptvupg.com/feed.xml",
      "application/atom+xml": "https://www.iptvupg.com/atom.xml",
    },
  },
  openGraph: {
    title: "The Best IPTV Service of 2026 — 24,000+ Channels in 4K From $7.50/mo",
    description:
      "Premium IPTV with anti-freeze 4K streaming on every device. Free trial, no credit card. 99.9% uptime. Trusted by 6,000+ subscribers worldwide.",
    url: "https://www.iptvupg.com",
    siteName: "IPTV UPG",
    locale: "en_US",
    type: "website",
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "The Best IPTV Service of 2026 — 24,000+ Channels in 4K From $7.50/mo",
    description:
      "Premium IPTV with anti-freeze 4K streaming on every device. Free trial, no credit card. 7-day money-back guarantee.",
    creator: "@iptvupg",
    // Twitter image auto-generated by src/app/opengraph-image.tsx
  },
  // Icons auto-generated by src/app/favicon.ico and src/app/apple-icon.tsx
  verification: {
    google: "LXDSwIvN3mXf1qYEo-JF4Ogw3siEy2bAttxXtkCyv_Y",
    other: {
      "msvalidate.01": "CEC29E9356C1B062CC9637E64D68C778",
    },
  },
};

// Site-wide JSON-LD: Organization + WebSite anchors. Page-level @graph blocks
// reference these via @id (#organization, #website) so the entity graph is
// connected on every route, not just the homepage.
const globalEntitySchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://www.iptvupg.com/#organization",
      name: "IPTV UPG",
      url: "https://www.iptvupg.com",
      logo: {
        "@type": "ImageObject",
        "@id": "https://www.iptvupg.com/#logo",
        url: "https://www.iptvupg.com/opengraph-image",
        width: 1200,
        height: 630,
        caption: "IPTV UPG — Best IPTV Service",
      },
      sameAs: [
        "https://twitter.com/iptvupg",
        "https://instagram.com/iptvupg",
        "https://www.trustpilot.com/review/iptvupg.com",
        "https://www.youtube.com/@IPTVUPG",
        "https://www.facebook.com/iptvupg",
        "https://www.linkedin.com/company/iptvupg",
        "https://www.crunchbase.com/organization/iptv-upg",
      ],
    },
    {
      "@type": "WebSite",
      "@id": "https://www.iptvupg.com/#website",
      name: "IPTV UPG",
      alternateName: "IPTVUPG",
      url: "https://www.iptvupg.com",
      publisher: { "@id": "https://www.iptvupg.com/#organization" },
      inLanguage: "en",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`}>
      <body className="min-h-screen font-sans">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(globalEntitySchema) }}
        />
        <a href="#main-content" className="skip-link">
          Skip to main content
        </a>
        {children}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
      </body>
    </html>
  );
}
